# Generated by Django 6.0.6 on 2026-07-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousemanager',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
