# Generated by Django 6.0.6 on 2026-07-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0002_warehousemanager_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
