# Generated by Django 6.0.6 on 2026-07-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehousemanager',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
    ]
